#!/usr/bin/env python3

import sys, signal, os

sys.path.insert(1, '/usr/local/lib/python3.4/site-packages')

from gi.repository import Gio, Gtk
from bolt.application import Bolt

pkgdatadir = '/usr/local/share/bolt'

if __name__ == "__main__":
	resource = Gio.resource_load(os.path.join(pkgdatadir, "bolt.gresource"))
	Gio.Resource._register(resource)

	app = Bolt()
	signal.signal(signal.SIGINT, signal.SIG_DFL)
	print("Running App...")
	exit = app.run()
	sys.exit(exit)